# CREDIT CARD FRAUD DETECTION USING PYTHON

### CASE STUDY

In [1]:
# IMPORTING USING PYTHON
import warnings
warnings.filterwarnings('ignore')

## EDA

In [2]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix



In [3]:
from sklearn.svm import SVC

In [4]:
# Load the dataset
df = pd.read_csv("C:/Users/uwaom/Desktop/credit card/creditcard.csv")

In [5]:
df.head(10) # DISPLAYS FIRST 10 ROWS

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
5   2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728  0.476201   
6   4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708 -0.005159   
7   7.0 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118  1.120631   
8   7.0 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818  0.370145   
9   9.0 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761  0.651583   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   
5  0.260314 -0.568671  ... -0.208254 -0.559825 -0.026398 -0.371427 -0.232794   
6  0.081213  0.464960  ... -0.167716 -0.270710 -0.154104 -0.780055  0.750137   
7 -3.807864  0.615375  ...  1.943465 -1.015455  0.057504 -0.649709 -0.415267   
8  0.851084 -0.392048  ... -0.073425 -0.268092 -0.204233  1.011592  0.373205   
9  0.069539 -0.736727  ... -0.246914 -0.633753 -0.120794 -0.385050 -0.069733   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  
5  0.105915  0.253844  0.081080    3.67      0  
6 -0.257237  0.034507  0.005168    4.99      0  
7 -0.051634 -1.206921 -1.085339   40.80      0  
8 -0.384157  0.011747  0.142404   93.20      0  
9  0.094199  0.246219  0.083076    3.68      0  

[10 rows x 31 columns]

In [6]:
df.tail(10) # DISPLAYS LAST 10 ROWS

Time         V1         V2        V3        V4        V5  \
284797  172782.0  -0.241923   0.712247  0.399806 -0.463406  0.244531   
284798  172782.0   0.219529   0.881246 -0.635891  0.960928 -0.152971   
284799  172783.0  -1.775135  -0.004235  1.189786  0.331096  1.196063   
284800  172784.0   2.039560  -0.175233 -1.196825  0.234580 -0.008713   
284801  172785.0   0.120316   0.931005 -0.546012 -0.745097  1.130314   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
284797 -1.343668  0.929369 -0.206210  0.106234  ... -0.228876 -0.514376   
284798 -1.014307  0.427126  0.121340 -0.285670  ...  0.099936  0.337120   
284799  5.519980 -1.518185  2.080825  1.159498  ...  0.103302  0.654850   
284800 -0.726571  0.017050 -0.118228  0.435402  ... -0.268048 -0.717211   
284801 -0.235973  0.812722  0.115093 -0.204064  ... -0.314205 -0.808520   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
284797  0.279598  0.371441 -0.559238  0.113144  0.131507  0.081265    5.49   
284798  0.251791  0.057688 -1.508368  0.144023  0.181205  0.215243   24.05   
284799 -0.348929  0.745323  0.704545 -0.127579  0.454379  0.130308   79.99   
284800  0.297930 -0.359769 -0.315610  0.201114 -0.080826 -0.075071    2.68   
284801  0.050343  0.102800 -0.435870  0.124079  0.217940  0.068803    2.69   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
284797      0  
284798      0  
284799      0  
284800      0  
284801      0  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[10 rows x 31 columns]

In [7]:
pd.set_option('display.max_columns', None) # DISPLAYS ALL COLUMNS

In [8]:
df.head(10)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
5   2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728  0.476201   
6   4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708 -0.005159   
7   7.0 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118  1.120631   
8   7.0 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818  0.370145   
9   9.0 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761  0.651583   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   
5  0.260314 -0.568671 -0.371407  1.341262  0.359894 -0.358091 -0.137134   
6  0.081213  0.464960 -0.099254 -1.416907 -0.153826 -0.751063  0.167372   
7 -3.807864  0.615375  1.249376 -0.619468  0.291474  1.757964 -1.323865   
8  0.851084 -0.392048 -0.410430 -0.705117 -0.110452 -0.286254  0.074355   
9  0.069539 -0.736727 -0.366846  1.017614  0.836390  1.006844 -0.443523   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   
5  0.517617  0.401726 -0.058133  0.068653 -0.033194  0.084968 -0.208254   
6  0.050144 -0.443587  0.002821 -0.611987 -0.045575 -0.219633 -0.167716   
7  0.686133 -0.076127 -1.222127 -0.358222  0.324505 -0.156742  1.943465   
8 -0.328783 -0.210077 -0.499768  0.118765  0.570328  0.052736 -0.073425   
9  0.150219  0.739453 -0.540980  0.476677  0.451773  0.203711 -0.246914   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   
5 -0.559825 -0.026398 -0.371427 -0.232794  0.105915  0.253844  0.081080   
6 -0.270710 -0.154104 -0.780055  0.750137 -0.257237  0.034507  0.005168   
7 -1.015455  0.057504 -0.649709 -0.415267 -0.051634 -1.206921 -1.085339   
8 -0.268092 -0.204233  1.011592  0.373205 -0.384157  0.011747  0.142404   
9 -0.633753 -0.120794 -0.385050 -0.069733  0.094199  0.246219  0.083076   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0  
5    3.67      0  
6    4.99      0  
7   40.80      0  
8   93.20      0  
9    3.68      0

In [9]:
df.shape # DISPLAYS NUMBER OF ROWS AND COLUMNS

(284807, 31)

In [10]:
# Returns the datatype of every row in the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [11]:
# Returns row(s) with with missing values 
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [12]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

#### In this Dataset, there seems to be more non-fraudulent transactions than Fraudulent which makes the dataset imbalanced

## Exploring Dataset (Finding Statistical Info)

In [13]:
# Explore the dataset
# print(df.info())
print(df.describe())

# Handle missing values (if any)
df = df.dropna()



                Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.23709

## Feature Selection and Feature Scaling

In [14]:
# Scale the numerical features
scaler = StandardScaler()
X = scaler.fit_transform(df.drop('Class', axis=1))
y = df['Class']



## Train Test Split

In [15]:
# Split the dataset into training, and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)




## Model Selection and Training (Fitting the Train Set into the Model)

## LOGISTIC REGRESSION

In [16]:
# Logistic Regression
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)



LogisticRegression()

## Making Predictions on the Test Set

In [17]:
# Test Set
# Model Evaluation
# Logistic Regression
lr_test_acc = accuracy_score(y_test, lr_model.predict(X_test))
lr_test_precision = precision_score(y_test, lr_model.predict(X_test))
lr_test_recall = recall_score(y_test, lr_model.predict(X_test))
lr_test_f1 = f1_score(y_test, lr_model.predict(X_test))

print("Logistic Regression Test Metrics:")
print(f"Accuracy: {lr_test_acc:.4f}")
print(f"Precision: {lr_test_precision:.4f}")
print(f"Recall: {lr_test_recall:.4f}")
print(f"F1-score: {lr_test_f1:.4f}")



Logistic Regression Test Metrics:
Accuracy: 0.9990
Precision: 0.7778
Recall: 0.5833
F1-score: 0.6667


#### The Accuracy is very high, as the same as the Precision, but for the Recall and F1-Score the values are not that low but it will be boosted later

### Calibrating the Logistic Regression Model with Isotonic Regression for Optimal Performance

In [18]:
from sklearn.calibration import CalibratedClassifierCV

# Logistic Regression with Isotonic Regression calibration
lr_model = LogisticRegression(class_weight='balanced')
lr_model.fit(X_train, y_train)

# Calibrate the Logistic Regression model using Isotonic Regression
calibrated_lr_model = CalibratedClassifierCV(lr_model, method='isotonic', cv='prefit')
calibrated_lr_model.fit(X_train, y_train)

y_pred_proba = calibrated_lr_model.predict_proba(X_test)
y_pred = (y_pred_proba[:, 1] > 0.5).astype(int)  # Adjust the threshold as needed

lr_test_acc = accuracy_score(y_test, y_pred)
lr_test_precision = precision_score(y_test, y_pred)
lr_test_recall = recall_score(y_test, y_pred)
lr_test_f1 = f1_score(y_test, y_pred)

print("Logistic Regression Test Metrics (Calibrated with Isotonic Regression):")
print(f"Accuracy: {lr_test_acc:.4f}")
print(f"Precision: {lr_test_precision:.4f}")
print(f"Recall: {lr_test_recall:.4f}")
print(f"F1-score: {lr_test_f1:.4f}")

print("\n")

print("Confusion Matrix for Test Set:")
con_mat_lr = confusion_matrix(y_test, lr_model.predict(X_test))
print(con_mat_lr)

Logistic Regression Test Metrics (Calibrated with Isotonic Regression):
Accuracy: 0.9991
Precision: 0.7558
Recall: 0.6771
F1-score: 0.7143


Confusion Matrix for Test Set:
[[55665  1201]
 [   12    84]]


#### Here's the Performance Metrics on the Test Set showing that there's Improvement compared to the previous Result Metrics.

## RANDOM FOREST

In [20]:
# Random Forest
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)



RandomForestClassifier()

## Making Predictions on the Test Set

In [21]:
# Test Set
# Random Forest
rf_test_acc = accuracy_score(y_test, rf_model.predict(X_test))
rf_test_precision = precision_score(y_test, rf_model.predict(X_test))
rf_test_recall = recall_score(y_test, rf_model.predict(X_test))
rf_test_f1 = f1_score(y_test, rf_model.predict(X_test))

print("Random Forest Test Metrics:")
print(f"Accuracy: {rf_test_acc:.4f}")
print(f"Precision: {rf_test_precision:.4f}")
print(f"Recall: {rf_test_recall:.4f}")
print(f"F1-score: {rf_test_f1:.4f}")

print("\n")

print("Confusion Matrix for Test Set:")
con_mat_rf = confusion_matrix(y_test, rf_model.predict(X_test))
print(con_mat_rf)

Random Forest Test Metrics:
Accuracy: 0.9993
Precision: 0.8500
Recall: 0.7083
F1-score: 0.7727


Confusion Matrix for Test Set:
[[56854    12]
 [   28    68]]


In [22]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

## Support Vector Machine

In [23]:
# Support Vector Machine
svc_model = SVC()
svc_model.fit(X_train, y_train)



SVC()

## Making Predictions on the Test Set

In [24]:
# Test Set
# Support Vector Classifier
svc_test_acc = accuracy_score(y_test, svc_model.predict(X_test))
svc_test_precision = precision_score(y_test, svc_model.predict(X_test))
svc_test_recall = recall_score(y_test, svc_model.predict(X_test))
svc_test_f1 = f1_score(y_test, svc_model.predict(X_test))

print("Random Forest Test Metrics")
print(f"Accuracy: {svc_test_acc:.4f}")
print(f"Precision: {svc_test_precision:.4f}")
print(f"Recall: {svc_test_recall:.4f}")
print(f"F1-score: {svc_test_f1:.4f}")

print("\n")

print("Confusion Matrix for Test Set:")
con_mat_svc = confusion_matrix(y_test, svc_model.predict(X_test))
print(con_mat_svc)

Random Forest Test Metrics
Accuracy: 0.9992
Precision: 0.9194
Recall: 0.5938
F1-score: 0.7215


Confusion Matrix for Test Set:
[[56861     5]
 [   39    57]]


#### All models achieved high accuracies but it is not reliable because Credit Card Fraud Cases are very sensitive and due to the fact that there were less fraud cases but other Performance metrics like the Precision, Recall and F1-Score will give a better insight.

#### From above, the best performing model is all together is Random Forest, followed by Spport Vector Classifier then Logistic Regression.